apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      volumes:
        - name: shared
          persistentVolumeClaim:
            claimName: shared-volume-claim-1
      containers:
        - name: todo-app
          image: docker.io/pjmartin/todo-app:2.2@sha256:eb882290c4c6c85786854ec37b7c5f9501f217c423fae6753e5e68d557319139
          volumeMounts:
            - name: shared
              mountPath: /app/data
          env:
            - name: TODO_BACKEND_URL
              value: "http://todo-backend-svc:2345"
            - name: DATA_ROOT
              value: "/app/data"