apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-pong-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pingpong
  template:
    metadata:
      labels:
        app: pingpong
    spec:
      volumes:
        - name: shared
          persistentVolumeClaim:
            claimName: shared-volume-claim-0
      containers:
        - name: pingpong
          ports:
            - name: http
              containerPort: 3000
          image: docker.io/pjmartin/pingpong:1.12@sha256:27cccdbb73f65886a231e647594616978bc840f705bbdfafc983ae7e5e0ec76c
          volumeMounts:
            - name: shared
              mountPath: /app/data
          env:
            - name: DATA_ROOT
              value: "/app/data"
