---
apiVersion: v1
kind: ConfigMap
metadata:
  name: log-output-config
data:
   DATA_ROOT:           "/app/data"
   POSTGRES_HOST:       "postgres-svc.database"
   POSTGRES_PORT:       "5432"
   POSTGRES_DB:         "postgres"
   POSTGRES_USER:       "postgres"
   PORT:                "3000"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-pong-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pingpong
  template:
    metadata:
      labels:
        app: pingpong
    spec:
      # imagePullSecrets:
      #   - name: regcred
      containers:
        - name: pingpong
          image: docker.io/pjmartin/pingpong:3.1@sha256:ad21bf3ec6916a88f0bb7f03cf6fd27e85d347437c7c56ecb98f91ffa015f2c9
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: log-output-config
            - secretRef:
                name: ping-pong-secrets
