---
apiVersion: v1
kind: ConfigMap
metadata:
  name: log-output-config
data:
   DATA_ROOT:           "/app/data"
   POSTGRES_HOST:       "postgres-svc.database"
   POSTGRES_PORT:       "5432"
   POSTGRES_DB:         "postgres"
   POSTGRES_USER:       "postgres"
   PORT:                "3000"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-pong-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pingpong
  template:
    metadata:
      labels:
        app: pingpong
    spec:
      containers:
        - name: pingpong
          image: docker.io/pjmartin/pingpong:2.7@sha256:c8df613bd2b14dad8baf103a20823af0fe084d724b86a7f46ab0ed0a5f0dae4d
          envFrom:
            - configMapRef:
                name: log-output-config
            - secretRef:
                name: ping-pong-secrets
