apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-pong-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pingpong
  template:
    metadata:
      labels:
        app: pingpong
    spec:
      volumes:
        - name: ping-output
          persistentVolumeClaim:
            claimName: shared-volume-claim-0
      containers:
        - name: pingpong
          ports:
            - name: http
              containerPort: 3000
          image: pjmartin/pingpong:1.9
          volumeMounts:
            - name: ping-output
              mountPath: /app/logs
          env:
            - name: LOG_PATH
              value: "/app/logs/ping-pong.log"
