apiVersion: alb.networking.azure.io/v1
kind: HealthCheckPolicy
metadata:
  name: ping-pong-health
  namespace: exercises
spec:
  targetRef:
    group: ""          # core API group
    kind: Service
    name: ping-pong-svc
    namespace: exercises
  default:
    interval: 5s
    timeout: 5s
    healthyThreshold: 1
    unhealthyThreshold: 3
    port: 80
    http:
      host: localhost
      path: /health        # <- your app returns 200 here
      match:
        statusCodes:
        - start: 200
          end: 399
