apiVersion: v1
kind: ConfigMap
metadata:
  name: log-output-config
  namespace: exercises
data:
  information.txt: |
    NEW MESSAGE IN FILE!
  MESSAGE: "Hello Message variable!"
  PING_PONG_URL: "http://ping-pong-svc:80/pings"