apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logoutput
  template:
    metadata:
      labels:
        app: logoutput
    spec:
      volumes:
        - name: log-output
          persistentVolumeClaim:
            claimName: shared-volume-claim-0
      containers:
        - name: log-reader
          image: pjmartin/log-reader:1.11.3
          ports:
            - name: http
              containerPort: 3000
          imagePullPolicy: Always
          env:
            - name: LOG_FILE
              value: "/app/logs/log_output.log"
            - name: PING_PONG_LOG_FILE
              value: "/app/logs/ping-pong.log"
          volumeMounts:
            - name: log-output
              mountPath: /app/logs

        - name: log-writer
          image: pjmartin/log-writer:1.10
          imagePullPolicy: Always
          env:
            - name: LOG_FILE
              value: "/app/logs/log_output.log"
          volumeMounts:
            - name: log-output
              mountPath: /app/logs