apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-volume
  namespace: exercises
spec:
  storageClassName: managed-csi
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output-deployment
  namespace: exercises
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: logoutput
  template:
    metadata:
      labels:
        app: logoutput
    spec:
      volumes:
        - name: shared-storage
          persistentVolumeClaim:
            claimName: shared-volume
        - name: config-volume
          configMap:
            name: log-output-config
      containers:
        - name: log-reader
          image: docker.io/pjmartin/log-reader:3.2@sha256:3fd3fcbb749acfe030004ff33d8c01feee671f2cc3e30a5ec2cb5fd902c69ddb
          ports:
            - name: http
              containerPort: 3000
          volumeMounts:
            - name: shared-storage
              mountPath: /app/data
            - name: config-volume
              mountPath: /app/config/
          env:
            - name: DATA_ROOT
              value: "/app/data"
            - name: CONFIG_ROOT
              value: "/app/config"
          envFrom:
            - configMapRef:
                name: log-output-config

        - name: log-writer
          image: docker.io/pjmartin/log-writer:3.2@sha256:bdd18ca3cccb288a7f7532d26876e4874fa771f00fc8e37d7fbf32e1b95a0243
          volumeMounts:
            - name: shared-storage
              mountPath: /app/data
          env:
            - name: DATA_ROOT
              value: "/app/data"
