apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logoutput
  template:
    metadata:
      labels:
        app: logoutput
    spec:
      volumes:
        - name: shared
          persistentVolumeClaim:
            claimName: shared-volume-claim-0
      containers:
        - name: log-reader
          image: docker.io/pjmartin/log-reader:1.12@sha256:769a55b244cab86f70425b327a816e8de43fe4088a237fe439bfde2c0aad1e6d
          ports:
            - name: http
              containerPort: 3000
          imagePullPolicy: Always
          volumeMounts:
            - name: shared
              mountPath: /app/data
          env:
            - name: DATA_ROOT
              value: "/app/data"

        - name: log-writer
          image: docker.io/pjmartin/log-writer:1.12@sha256:69aa6a0250ff7200ed0cfcada2dddec238a0dab190ffe553941444cc46fa3891
          imagePullPolicy: Always
          volumeMounts:
            - name: shared
              mountPath: /app/data
          env:
            - name: DATA_ROOT
              value: "/app/data"