apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logoutput
  template:
    metadata:
      labels:
        app: logoutput
    spec:
      containers:
        - name: log-reader
          image: docker.io/pjmartin/log-reader:2.1@sha256:345499cd74f32cad14e5e2266f3bc5fa0aea0aefc2165a82c2a107158b0a9219
          ports:
            - name: http
              containerPort: 3000
          imagePullPolicy: Always
          env:
            - name: DATA_ROOT
              value: "/app/data"

        - name: log-writer
          image: docker.io/pjmartin/log-writer:1.12@sha256:69aa6a0250ff7200ed0cfcada2dddec238a0dab190ffe553941444cc46fa3891
          imagePullPolicy: Always
          env:
            - name: DATA_ROOT
              value: "/app/data"
