apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logoutput
  template:
    metadata:
      labels:
        app: logoutput
    spec:
      volumes:
        - name: shared-storage
          persistentVolumeClaim:
            claimName: shared-volume-claim-0
      containers:
        - name: log-reader
          image: docker.io/pjmartin/log-reader:2.3@sha256:ce70245033939b68ff3a8cbde73c8daa42960033fa27ce874df21955c11e41af
          ports:
            - name: http
              containerPort: 3000
          volumeMounts:
            - name: shared-storage
              mountPath: /app/data
          env:
            - name: DATA_ROOT
              value: "/app/data"

        - name: log-writer
          image: docker.io/pjmartin/log-writer:2.3@sha256:6bb942841a896eb784f8e8c6c05b8d517ff272e2c03ae58ae372e08d0e01d1db
          volumeMounts:
            - name: shared-storage
              mountPath: /app/data
          env:
            - name: DATA_ROOT
              value: "/app/data"
