apiVersion: v1
kind: Service
metadata:
  name: log-output-svc
spec:
  type: ClusterIP
  selector:
    app: logoutput
  ports:
    - name: http
      port: 2345
      protocol: TCP
      targetPort: http