apiVersion: v1
kind: ConfigMap
metadata:
  name: todo-backend-config
data:
  PORT: "3000"
  CORS_ORIGINS: "*"
  POSTGRES_HOST: "postgres-svc.database"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "postgres"
  POSTGRES_USER: "postgres"