apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todoapp
  template:
    metadata:
      labels:
        app: todoapp
    spec:
      containers:
        - name: todoapp
          ports:
            - name: http
              containerPort: 3000
          image: pjmartin/todo_app:1.11
          imagePullPolicy: Always
          env:
            - name: PORT
              value: "3000"
