apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todoapp
  template:
    metadata:
      labels:
        app: todoapp
    spec:
      volumes:
        - name: shared
          persistentVolumeClaim:
            claimName: shared-volume-claim-0
      containers:
        - name: todoapp
          ports:
            - name: http
              containerPort: 3000
          image: docker.io/pjmartin/todo_app:1.13@sha256:c9b2e2be2155ca0b158d0aaea9ce2bf3959a1fa80bdae3c13325d32fc53852d7
          volumeMounts:
            - name: shared
              mountPath: /app/data
          env:
            - name: PORT
              value: "3000"
            - name: DATA_ROOT
              value: "/app/data"