apiVersion: v1
kind: Secret
metadata:
    name: postgres-secrets
    namespace: database
data:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:JicqaYszRn2u1ahy3N2BZuSjEGQolDR507XrK+RotUp4Ut3mEiGXLmZXeY2PaJr3,iv:JD06x07P8DZkXO6Sets/HJqKdu4f5w1Dh2pBWIpDrxc=,tag:LlyVMhBcOPbSPrgRJp/Emg==,type:str]
sops:
    age:
        - recipient: age1wsr3rdtqqxavunugdf78d4cfqxrp0flu58gy7xtvdpk558hud3ns7wdmjp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAweHdGUmdnRG93c2JHT0Fk
            cmM4cElnMXFBTTBrY1FDTE1aSGtNZkZwVEQ0ClBUSncwc0JIQWJWZHV2eENIc0JC
            bkhhSkNqTnQ1MHYzZGVhOFdxNnNlL1UKLS0tIG9Pb21BTHdjOVFGUW50MGpnVzNi
            NFpGL2FGZWhrbzhBMkFWS3RQclcyRTQK3H2d0/SXua28w0+/WWmi2cAo6aekUyNR
            CXWsdvx/tkPGirSLtIJsah5aUIG1sgi0b98/Ui8HwAF21T9FpUQ8TQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-15T11:22:39Z"
    mac: ENC[AES256_GCM,data:JPRuBFtukztCoa+lTJGRD/m7QaUiI7rWdRXw8GwC48Sl2P+aQkykcthyThNTDq5p2lF7y/QyWKA7e+A4TBDMqDvSJ8Z8HmcjNje6sb53csayNvP+bnX35OBrsUUkhjEloPRV6XTu7+zSFLbQGaqm+X4BNEMEcYGJLHURhNaekoo=,iv:Ar1CJ4tmfwnkZviKQHaF5Imnck32QUgyWe0mmywd6Y8=,tag:6AaZgs1/m60MU+xbM7IL8A==,type:str]
    encrypted_regex: ^(data)$
    version: 3.11.0
